import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchTasks } from "../redux/task.thunk";
import TaskItem from "../components/TaskItem/TaskItem";
import TaskForm from "../components/TaskForm";
import Chart from "../components/Chart";
import { selectTasks } from "../redux/task.selector";
import styled from "@emotion/styled";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const tasks = useSelector(selectTasks);

  useEffect(() => {
    dispatch(fetchTasks());
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Task App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>My Task</h1>
      </header>
      <MainSection>
        <Chart />
        <div>
          <TaskForm />
          {tasks && tasks.map((task) => <TaskItem key={task.id} {...task} />)}
        </div>
      </MainSection>
    </div>
  );
};

export default Home;

const MainSection = styled("main")`
  padding: 2rem;
  display: flex;
  max-width: 900px;
  align-items: center;
  width: 100%;

  & > :nth-of-type(2) {
    flex: 1;
    margin-left: 20px;
  }

  @media (max-width: 650px) {
    flex-direction: column;
    & > :nth-of-type(2) {
      margin-top: 20px;
      margin-left: 0;
    }
  }
`;
